### ISSUE TITLE
Document broker pre-requisites

### ISSUE THREAD

**Issue by p5** [aws/aws-msk-iam-sasl-signer-js#17]
### Describe the issue

Unsure whether this is a bug, or a documentation issue.  

We are trying to implement this library - migrating from https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism - but are facing an issue when connecting to our provisioned MSK Kafka v3.3.1 cluster using this library.  

Our cluster has IAM authentication enabled, which was working with the above package, but with `aws-msk-iam-sasl-signer-js`, we are facing an "unsupported" error when specifying `oauthbearer`.

If this library is only supported with a specific version of MSK, or if there are some other pre-requisites to using this package, it would be helpful to document these.

Full log:
<details>

```
aws-sasl-signer npm start

> aws-sasl-signer@1.0.0 start
> node index.js

{"level":"WARN","timestamp":"2023-11-14T10:39:14.314Z","logger":"kafkajs","message":"KafkaJS v2.0.0 switched default partitioner. To retain the same partitioning behavior as in previous versions, create the producer with the option \"createPartitioner: Partitioners.LegacyPartitioner\". See the migration guide at https://kafka.js.org/docs/migration-guide-v2.0.0#producer-new-default-partitioner for details. Silence this warning by setting the environment variable \"KAFKAJS_NO_PARTITIONER_WARNING=1\""}
{"level":"ERROR","timestamp":"2023-11-14T10:39:14.649Z","logger":"kafkajs","message":"[Connection] Response SaslHandshake(key: 17, version: 1)","broker":"b-3.commonmsk.gwbjum.c4.kafka.eu-west-1.amazonaws.com:9098","clientId":"my-app","error":"The broker does not support the requested SASL mechanism","correlationId":1,"size":23}
{"level":"ERROR","timestamp":"2023-11-14T10:39:14.649Z","logger":"kafkajs","message":"[BrokerPool] The broker does not support the requested SASL mechanism","retryCount":0,"retryTime":300}
KafkaJSProtocolError: The broker does not support the requested SASL mechanism
    at createErrorFromCode (/home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/protocol/error.js:581:10)
    at Object.parse (/home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/protocol/requests/saslHandshake/v0/response.js:24:11)
    at Connection.send (/home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/network/connection.js:433:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SASLAuthenticator.authenticate (/home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/broker/saslAuthenticator/index.js:35:23)
    at async /home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/network/connection.js:139:9
    at async Connection.authenticate (/home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/network/connection.js:315:5)
    at async Broker.connect (/home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/broker/index.js:111:7)
    at async /home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/cluster/brokerPool.js:93:9
    at async /home/admin/tmp/aws-sasl-signer/node_modules/kafkajs/src/cluster/index.js:107:14 {
  retriable: false,
  helpUrl: undefined,
  type: 'UNSUPPORTED_SASL_MECHANISM',
  code: 33,
  [cause]: undefined
}
```

</details>

### Links

- https://github.com/aws/aws-msk-iam-sasl-signer-js?tab=readme-ov-file#troubleshooting
- https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

**Comment by agarwal1510** [comment]
@p5 Thank you for bringing this up. Currently `SASL/OAUTHBEARER` mechanism works with newly created MSK Provisioned clusters (given IAM is enabled and Kafka version above 2.7.1) and any existing or new MSK Serverless clusters. The feature is being applied to existing MSK Provisioned cluster in the scheduled monthly security update. 
More information here: https://aws.amazon.com/blogs/big-data/amazon-msk-iam-authentication-now-supports-all-programming-languages/

Note, https://github.com/jmaver-plume/kafkajs-msk-iam-authentication-mechanism uses `SASL/AWS_MSK_IAM` mechanism which is why it was working as expected.

I would suggest you to try it on a newly created cluster or wait for the monthly security update.

**Comment by p5** [comment]
Thank you for clearing this up.  I guess everybody will be supported after a month, so documentation may not be worth it.

This is a great release!  We can now depend on an official package for IAM authentication in our services, rather than an unofficial one (having said that, the unofficial package has been amazing so far).  

Happy to close this issue as "Complete", but you may wish to leave it open so others can see your response.  I'll leave it to you :smile:
