### ISSUE TITLE
Publish the package to NPM registry

### ISSUE THREAD

**Issue by miron4dev** [aws/aws-msk-iam-sasl-signer-js#20]
### Describe the feature

I want to have the option to install the library from the NPM registry and not only GitHub.

### Use Case

In our organization, we install all libraries from our private registry which has mirrored dependencies from https://npmjs.com/
The current setup with installing a GitHub dependency requires us to implement a workaround to make it work in CI.

### Proposed Solution

Publish the package to https://npmjs.com

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### aws-msk-iam-sasl-signer-js library version used

1.0.0

### Environment details (OS name and version, etc.)

macOS

**Comment by sankalpbhatia** [comment]
Hi @miron4dev, we already have this release hosted in npm:  https://www.npmjs.com/package/aws-msk-iam-sasl-signer-js 
Let me know if you face any issues using it. 

`npm install aws-msk-iam-sasl-signer-js` should work. @agarwal1510 we may want to change our README here as well.
